services:
  llm-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-collector
    ports:
      - "9000:9000"             # host:container
    environment:
      # Must match the extension's API key
      - API_KEY=<your key here>
      # Optional: tune Flask/Gunicorn if your app reads these
      - PYTHONUNBUFFERED=1
    volumes:
      # Bind-mount your local repo into the container so logs/state/snapshots live on your disk.
      - /Users/kevinharlan/llm_collector:/workspace/llm_collector:rw
    # Make sure the working directory is your repo root inside the container
    working_dir: /workspace/llm_collector
    # Healthcheck (simple): hit /counters so Compose shows healthy once live
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/counters || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped
